### ISSUE TITLE
Selecting Indian Currency from picker showing 0 in symbol?

### ISSUE THREAD

**Issue by iAmVishal16** [midorikocak/currency-picker-android#13]
![Screen Shot 2019-04-30 at 3 32 25 PM](https://user-images.githubusercontent.com/34365396/56954966-c4d5fe80-6b5d-11e9-9132-0a8ec20607f1.png)

**Comment by Binary-Finery** [comment]
I've just noticed this issue also, simple work around
(pseudo-code)...

if (code.equals("INR")) symbol = [rupee symbol]

**Comment by iAmVishal16** [comment]
Already do that. Just pointing it out.
