### ISSUE TITLE
ExtendedCurrency object is null when trying to fetch data

### ISSUE THREAD

**Issue by ritesh-dubey** [midorikocak/currency-picker-android#2]
Trying to fetch ExtendedCurrency object using:

`ExtendedCurrency currency = ExtendedCurrency.getCurrencyByISO("USD");`

The above code initializes currency object as null.
Can you please provide a possible solution to this issue?

**Comment by BanterClaus** [comment]
Seems to be an issue with the comparator in ExtendedCurrency. No time to do a PR to fix right now but I did a quick workaround this way:

`private static ExtendedCurrency getExtendedCurrencyByISO(String code) {
        List<ExtendedCurrency> allCurrencies = ExtendedCurrency.getAllCurrencies();
        code = code.toUpperCase();
        for (ExtendedCurrency currency : allCurrencies) {
            if (currency.getCode().equals(code)) {
                return currency;
            }
        }
        return null;
    }`

**Comment by midorikocak** [comment]
Thanks, I will try to reproduce it. A PR would be very good.

**Comment by ubaierbhat** [comment]
This issue can be closed as it has already been fixed and does not exist in v 1.2.1
