### ISSUE TITLE
For Indian Rupee it is showing 0

### ISSUE THREAD

**Issue by Sankarrockzz** [midorikocak/currency-picker-android#6]
Instead of showing the rupee symbol its show 0 ?

**Comment by Sankarrockzz** [comment]
this is the bug: in your extendedCurrency list,
`new ExtendedCurrency("INR", "India Rupee", "0", drawable.flag_inr);`
it should be like this 
`new ExtendedCurrency("INR", "India Rupee", "₹", drawable.flag_inr)`

**Comment by midorikocak** [comment]
Merged https://github.com/midorikocak/currency-picker-android/pull/5

**Comment by mavilla-vishnu** [comment]
It's still 0 for Indian rupee. Using Version 1.2.1
